version: '3.8'

services:
  nginx:
    build: ./nginx
    image: sklearn-deploy-web-nginx:1.0
    container_name: sklearn_web_nginx
    volumes:
      - ./frontend/dist:/home/app/web
    ports:
      - 1351:80
    depends_on:
      - backend
    networks:
      - sklearn

  backend:
    image: sklearn-deploy-web-backend:1.0
    container_name: sklearn_web_backend
    build: ./backend
    command: /usr/local/bin/gunicorn -c gunicorn.conf.py app:app --reload
    volumes:
      - ./backend:/usr/src/app
      - ./log:/data
    expose:
      - 5000
    networks:
      - sklearn

networks:
  sklearn:
      driver: bridge