version: '3.8'

services:
  nginx:
    build: ./nginx
    image: sklearn-deploy-web-nginx:1.0
    container_name: sklearn_web_nginx
    volumes:
      - ./app/static:/home/app/web/project/static
    ports:
      - 1337:80
    depends_on:
      - backend
    networks:
      - sklearn

  web:
    image: sklearn-deploy-web-backend:1.0
    container_name: intranet_web
    build: .
    command: /usr/local/bin/gunicorn -c gunicorn.conf.py app:app --reload
    volumes:
      - ./backend:/usr/src/app
    expose:
      - 5000
    networks:
      - sklearn

networks:
  intranet_dev:
      driver: bridge
      ipam:
          driver: default
          config:
              - subnet: "172.51.0.0/16"