version: '3.8'

services:
  # Reverse proxy, to access backend and frontend from the same domain
  nginx:
    build: ./nginx
    image: sklearn-deploy-web-nginx:1.0
    container_name: sklearn_web_nginx
    volumes:
      - ./frontend/dist:/home/app/web
    ports:
      - 1351:80
    depends_on:
      - backend
    networks:
      - sklearn

  # Backend: run the model and give back predictions
  backend:
    image: sklearn-deploy-web-backend:1.0
    container_name: sklearn_web_backend
    build: ./backend
    command: /usr/local/bin/gunicorn -c gunicorn.conf.py app:app --reload
    volumes:
      - ./backend:/usr/src/app
      - ./log:/data
    expose:
      - 5000
    networks:
      - sklearn

  # frontend: used to build the frontend code
  frontend-build:
    image: sklearn-deploy-web-frontend-build:1.0
    container_name: sklearn_web_frontend_build
    build: ./frontend
    command: yarn build
    volumes:
      - ./frontend:/app/src

networks:
  sklearn:
      driver: bridge