services:
  # Backend
  - type: web
    name: sklearn-predict-test-api
    runtime: python
    repo: https://github.com/ascherrer-em/sklearn-deploy-web.git # optional
    region: frankfurt # optional (defaults to oregon)
    plan: free # optional (defaults to starter instance type)
    branch: main # optional (defaults to master)
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    numInstances: 1 # optional (defaults to 1)
    healthCheckPath: /health
    envVars:
     - key: PYTHON_VERSION
       value: 3.11.0
  # A static site
  - type: web
    name: sklearn-predict-test-front
    runtime: static
    repo: https://github.com/ascherrer-em/sklearn-deploy-web.git # optional
    buildCommand: yarn build
    rootDir: frontend
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: false # optional
    envVars:
      - key: BACKEND_HOST
        fromService:
          type: web
          name: sklearn-predict-test-api
          property: host 
      - key: RENDER
        value: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    routes:
      - type: redirect
        source: /*
        destination: /index.html