services:
  # Backend
  - type: web
    name: sklearn-predict-test-api
    runtime: docker
    repo: https://github.com/ascherrer-em/sklearn-deploy-web.git # optional
    region: frankfurt # optional (defaults to oregon)
    plan: free # optional (defaults to starter instance type)
    dockerfilePath: ./Dockerfile_render # optional
    branch: main # optional (defaults to master)
    rootDir: backend
    numInstances: 1 # optional (defaults to 1)
    healthCheckPath: /health
  # A static site
  - type: web
    name: sklearn-predict-test-front
    runtime: static
    repo: https://github.com/ascherrer-em/sklearn-deploy-web.git # optional
    buildCommand: yarn build
    rootDir: frontend
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: false # optional
    envVars:
      - key: BACKEND_HOST
        fromService:
          type: web
          name: sklearn-predict-test-api
          property: host 
      - key: RENDER
        value: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    routes:
      - type: redirect
        source: /*
        destination: /index.html