from python:3.11-slim-bullseye

WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
COPY . .

RUN pip install -r requirements.txt

ENTRYPOINT ["/usr/src/entrypoint.sh"]
