bind = "0.0.0.0:10000"  # 10000 is the required port for render.com
reload = True
preload = True
worker = 1
worker_connexions = 5
debug = False
logfile = "/data/gunicorn_debug.log"
accesslog = "/data/gunicorn_access.log"
timeout = 300
